### ISSUE TITLE
'X' icon does not appear on 'day-dial' properly when not using 100% zoom level

### ISSUE THREAD

**Issue by mishahawthorn** [mishagp/PauseInMultiplayer#2]
I'm seeing inconsistent behavior for scaling and placement of the paused time indicator. Do recall seeing this before the 1.6 upgrade, for awareness.

Could also improve things by drawing the pause indicator under open menus too.

https://github.com/mishagp/PauseInMultiplayer/assets/6118330/f3e96720-cc76-438a-9617-92d2745ee886

**Comment by ath88** [comment]
It seems the X is offset to the left when zooming out from 100%, so it is not completely gone.

**Comment by mishahawthorn** [comment]
> It seems the X is offset to the left when zooming out from 100%, so it is not completely gone.

That seems to be my assessment as well, I'll tweak the issue title accordingly.

**Comment by xeru98** [comment]
Created a pull request: https://github.com/mishagp/PauseInMultiplayer/pull/11

**Comment by mishahawthorn** [comment]
Closed in #11.
